name: setup

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v6
      with:
        node-version: '24.x'

    - uses: pnpm/action-setup@v5
      name: setup pnpm
      with:
        version: 10.12.1
        run_install: false

    - name: create pnpm cache directory
      id: pnpm-cache
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_OUTPUT

    - uses: actions/cache@v5
      name: setup pnpm cache
      with:
        path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: install dependencies
      run: pnpm install
      shell: bash
